<?php

namespace AppBundle\Repository;

/**
 * SkinnyLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkinnyLinkRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $url
     * @return string
     */
    public function findSkinnyUrl(string $url) : string {
        return $this->findOneBy(['skinny_url' => $url]);
    }
}
